// Command pututuvectors emits doorbell tokens minted by the server's own
// pututu.Token, for the firmware's verifier to be checked against.
//
// Why this exists (server §10.2, client §7, test C-8): the device accepts a
// wake only if it can reproduce the server's MAC. Nothing else in the system
// tells you the two agree — a drift in the key handling, the counter's ASCII
// rendering, or the base64 truncation produces a doorbell that never rings,
// on a device that otherwise looks perfectly healthy. So the expected MACs are
// never hand-written: they come from internal/pututu, and the host tier
// asserts the C++ verifier accepts every one of them.
//
// Output: test/firmware/host/testdata/pututu.json, committed so the host tier
// needs no Go toolchain to run.
//
// Usage: go run ./tools/pututuvectors -out test/firmware/host/testdata/pututu.json
package main

import (
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"

	"github.com/tholent/chaskiwasi/internal/pututu"
)

// Vector is one token and everything the device needs to check it. The counter
// is a string because it is a uint64: JSON numbers are doubles, and the
// boundary cases here are exactly the ones a double would round away.
type Vector struct {
	Name    string `json:"name"`
	Why     string `json:"why"`
	KeyHex  string `json:"key_hex"`
	Counter string `json:"counter"`
	Token   string `json:"token"`
}

type file struct {
	Note    string   `json:"note"`
	Vectors []Vector `json:"vectors"`
}

// The provisioned pututu key is a random secret of unremarkable length; the
// short and long keys are here because RFC 2104 handles keys longer than the
// 64-byte block differently (it hashes them first), and that branch is
// otherwise never exercised by a real deployment — which is exactly the kind
// of branch that is wrong when someone finally rotates to a longer key.
var (
	typicalKey = []byte("a-provisioned-pututu-key-32-bytes")
	shortKey   = []byte("k")
	longKey    = []byte("this pututu key is deliberately longer than the sixty-four byte HMAC block size")
)

var cases = []struct {
	name, why string
	key       []byte
	counter   uint64
}{
	{"first", "counter 1: the first doorbell a freshly provisioned Wasi rings", typicalKey, 1},
	{"typical", "an unremarkable counter mid-life", typicalKey, 42},
	{"nine", "single digit, no rendering ambiguity to hide behind", typicalKey, 9},
	{"ten", "two digits: the ASCII rendering is what is MACed, not the integer", typicalKey, 10},
	{"large", "past 2^53, where a JSON number would have rounded", typicalKey, 9007199254740993},
	{"max_uint64", "the boundary the device's parser must not overflow through", typicalKey, 18446744073709551615},
	{"short_key", "a one-byte key: zero-padding to the block must still agree", shortKey, 7},
	{"long_key", "a key longer than the HMAC block, which RFC 2104 hashes first", longKey, 7},
	{"zero", "counter 0 is MAC-valid and still never accepted — high-water starts at 0", typicalKey, 0},
}

func main() {
	out := flag.String("out", "test/firmware/host/testdata/pututu.json", "output path")
	flag.Parse()

	f := file{
		Note: "Generated by tools/pututuvectors from internal/pututu — the server's own " +
			"token minter. Do not hand-edit. The firmware's verifier must accept every " +
			"one of these (server §10.2, client §7, test C-8).",
	}
	for _, c := range cases {
		f.Vectors = append(f.Vectors, Vector{
			Name:    c.name,
			Why:     c.why,
			KeyHex:  hex.EncodeToString(c.key),
			Counter: strconv.FormatUint(c.counter, 10),
			Token:   pututu.Token(c.counter, c.key),
		})
	}

	b, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, "marshal:", err)
		os.Exit(1)
	}
	b = append(b, '\n')

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, b, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d tokens to %s\n", len(f.Vectors), *out)
}
