// Command graphvectors emits grapheme-segmentation test vectors from the
// server's own segmenter, for the firmware to be checked against.
//
// Why this exists (client B.7): the server counts graphemes with rivo/uniseg
// and the device counts them with utf8proc. If the two disagree at a boundary,
// a letter the compose counter accepted gets a terminal `invalid` ack from the
// server — a "couldn't send" the child did nothing to deserve, for text that
// looked fine on screen. Rather than trusting two independent UAX #29
// implementations to agree, we generate vectors from the Go side and make C-9
// assert utf8proc reproduces them exactly. A Unicode-version skew then fails a
// test instead of failing a child.
//
// Output: test/firmware/host/testdata/graphemes.json, committed to the repo so
// the host tier needs no Go toolchain to run.
//
// Usage: go run ./tools/graphvectors -out test/firmware/host/testdata/graphemes.json
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/rivo/uniseg"
)

// Vector is one string plus the ground truth about it: the byte offsets of
// every grapheme-cluster boundary (including 0 and len), and the cluster count.
// The device must reproduce both exactly.
type Vector struct {
	Name       string `json:"name"`
	Why        string `json:"why"`
	Text       string `json:"text"`
	Boundaries []int  `json:"boundaries"`
	Count      int    `json:"count"`
}

type file struct {
	Note           string   `json:"note"`
	UnisegVersion  string   `json:"uniseg_version"`
	UnicodeVersion string   `json:"unicode_version"`
	Vectors        []Vector `json:"vectors"`
}

// uniseg exports no version constant, so the pairing is recorded here by hand.
// That is the point rather than a wart: C-9 compares these vectors against
// utf8proc's own reported Unicode version, so a bump on either side surfaces as
// a failing test instead of a letter the server silently rejects (B.7).
const (
	unisegModuleVersion = "v0.4.7"
	unisegUnicode       = "15.0.0"
)

// cases are chosen for the boundaries that actually break implementations, not
// for coverage theatre. Each carries the reason it is here.
var cases = []struct{ name, why, text string }{
	{"ascii", "the trivial case must still agree", "hello"},
	{"empty", "zero-length input is a real input", ""},
	{"combining_accent", "e + U+0301 is ONE cluster; counting runes says two", "café"},
	{"precomposed_vs_combining", "same glyph, different byte counts, both one cluster", "café café"},
	{"emoji_simple", "a single non-BMP emoji is one cluster, four bytes", "\U0001F600"},
	{"emoji_zwj_family", "ZWJ sequence: one perceived character, many code points", "\U0001F468‍\U0001F469‍\U0001F467‍\U0001F466"},
	{"emoji_skin_tone", "base + modifier is one cluster", "\U0001F44B\U0001F3FD"},
	{"flag_regional_indicator", "two regional indicators pair into one flag", "\U0001F1F5\U0001F1EA"},
	{"flag_pair_then_single", "an odd trailing indicator must not merge backwards", "\U0001F1F5\U0001F1EA\U0001F1FA"},
	{"keycap", "digit + FE0F + 20E3 is one cluster", "1️⃣"},
	{"devanagari", "consonant + vowel sign is one cluster", "कि"},
	{"hangul_jamo", "conjoining jamo compose into syllables", "각"},
	{"crlf", "CR LF is one cluster, deliberately", "a\r\nb"},
	{"mixed_letter", "a realistic letter mixing scripts and emoji", "Hola abuela! \U0001F44B\U0001F3FD Estoy bien — café ☕"},
	{"zwj_at_cap_boundary", "a cluster straddling a cap is where truncation goes wrong", "aaaa\U0001F468‍\U0001F469‍\U0001F467"},
}

func main() {
	out := flag.String("out", "test/firmware/host/testdata/graphemes.json", "output path")
	flag.Parse()

	f := file{
		Note: "Generated by tools/graphvectors from rivo/uniseg — the server's own " +
			"segmenter. Do not hand-edit. Regenerate whenever uniseg or utf8proc " +
			"changes Unicode version (client B.7, test C-9).",
		UnisegVersion:  unisegModuleVersion,
		UnicodeVersion: unisegUnicode,
	}

	for _, c := range cases {
		v := Vector{Name: c.name, Why: c.why, Text: c.text, Boundaries: []int{0}}
		state := -1
		rest := c.text
		pos := 0
		for len(rest) > 0 {
			var cluster string
			cluster, rest, _, state = uniseg.FirstGraphemeClusterInString(rest, state)
			pos += len(cluster)
			v.Boundaries = append(v.Boundaries, pos)
			v.Count++
		}
		f.Vectors = append(f.Vectors, v)
	}

	b, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, "marshal:", err)
		os.Exit(1)
	}
	b = append(b, '\n')

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, b, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d vectors to %s (Unicode %s)\n", len(f.Vectors), *out, f.UnicodeVersion)
}
